apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tfc-agent"
  # namespace: tfc
  labels:
    app: "tfc-agent"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "tfc-agent"
  template:
    metadata:
      labels:
        app: "tfc-agent"
    spec:
      containers:
        - name: "tfc-agent-0"
          #image: {{.Input.DockerImageFull}}
          image: ${artifact.image}:${artifact.tag}
          imagePullPolicy: Always
          env: 
          %{ for k,v in entrypoint.env }
            - name: ${k}
              value: "${v}"
          %{ endfor }      
            # {{range $key, $value := .Env}}
            # - name: {{$key}}
            #   value: "{{$value}}"
            # {{end}}

